"""하위 호환: 상수는 websync.core.update.constants 로 이동."""
from websync.core.update.constants import (
    UPDATE_ARTIFACT_MAX_BYTES,
    UPDATE_BACKUP_KEEP_COUNT,
    UPDATE_MANIFEST_MAX_BYTES,
    UPDATE_MANIFEST_URL,
    UPDATE_PUBLIC_KEY_B64,
    UPDATE_PUBLIC_KEY_B64_DEFAULT,
    UPDATE_RELEASES_URL,
    UPDATE_REQUEST_TIMEOUT_SECONDS,
)

__all__ = [
    "UPDATE_ARTIFACT_MAX_BYTES",
    "UPDATE_BACKUP_KEEP_COUNT",
    "UPDATE_MANIFEST_MAX_BYTES",
    "UPDATE_MANIFEST_URL",
    "UPDATE_PUBLIC_KEY_B64",
    "UPDATE_PUBLIC_KEY_B64_DEFAULT",
    "UPDATE_RELEASES_URL",
    "UPDATE_REQUEST_TIMEOUT_SECONDS",
]
